title: "ChinaGreat-Sec"
description: "IOT 网络安全社区 | IoT Cybersecurity Community"
theme: jekyll-theme-slate

header_pages:
  - index.md
  - vulnerabilities/index.md
  - tools/index.md
  - resources/index.md
  - writeups/index.md

plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

markdown: kramdown
